[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qpaa6gkjjscy68dv39una68nl3347z0rxhrhqyax27g45yrvjwlgclzmpja"]

[[validator_account]]
address = "tnam1qxgnegx3se9htr05982atux3ytr797s8av39s5vy"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "95.217.231.107:26656"

[validator_account.consensus_key]
pk = "tpknam1qr8rk0ysxhxd6wv9t3ngq3avv09xe5l9rlh0q5ams8vm9uqpcygfyye5qvt"
authorization = "signam1qzaha6qyn3674vjt2t382pd3lq7m8qaujcmfk28efu5e545pdkzmegaptawd46msm2w5au4ujdtkcqnjp3a2f96r403mzsmdsjyg34g92zwkqx"

[validator_account.protocol_key]
pk = "tpknam1qrzvugys0y86na9v9qyxgmdrxvlhjuy5w2kfnx9uv2maknf3hath28vhfx4"
authorization = "signam1qzpunhlhlhtnup8fne90p5a8x2yggrltvs2nns792p2a4wrvvjew3fnz4wur3cg6y8d2cxz0tyztf84kv8ff76m2csf3zradx3ztmdq2h905yd"

[validator_account.tendermint_node_key]
pk = "tpknam1qps2vj36yqsf38me7tttghuqwc5z2pma0ta5vyxm2yt5gw8rzl7jw2sud68"
authorization = "signam1qqfvfnjg4zc65z2qssdmur2myuxanw3q930wqv959phctdlu4myyjtc25q04rvj26c66rwlu6c5feqvaehd95f5hy0fss4nt2ql3t4q9ufsw0e"

[validator_account.eth_hot_key]
pk = "tpknam1qyplme0dnzqc9sghq0dgja67kf5gk7kss0gjt5a60zevprkxrc55hscc9n2es"
authorization = "signam1qxvzr2g3rzj8fanzvzkrysdhl327fwfhtsyy6skqe46ez63la5tfxm6w2jx7ceyh30yqk6j2yats389krqvmmkvsdnf2rwzw84y0jlj4qy74flnx"

[validator_account.eth_cold_key]
pk = "tpknam1qypxa2d45glgmx0gxp8s0pvx6gpefam63pu6neaa7zqjqhcyuxhnhwcqe7rqw"
authorization = "signam1q8e06yptjzluzgs0fyjn0xx6ayer03xeunplcmdqjsfzhjzn52va5rahf8myk7nf00zsmgapmdl0qpttxwnxy49au4w2p3s00zhla75fqqcwqfac"

[validator_account.metadata]
email = "node@stamper.network"
discord_handle = "jeongseup"
avatar = "https://raw.githubusercontent.com/cosmostation/chainlist/main/resource/cosmostation/cosmostation_black_bg(128x128).png"

[validator_account.signatures]
tpknam1qpaa6gkjjscy68dv39una68nl3347z0rxhrhqyax27g45yrvjwlgclzmpja = "signam1qqexqt6dve38f6ea70lhgvxccl2mgmu4wvl4n3r3fw3atknps6h94w2e06vm6lcytumsre5xll295flkyjpjmy48d7l0cuup25fd8tcdx43ktn"

[[bond]]
source = "tnam1qxgnegx3se9htr05982atux3ytr797s8av39s5vy"
validator = "tnam1qxgnegx3se9htr05982atux3ytr797s8av39s5vy"
amount = "2631549"

[bond.signatures]
tpknam1qpaa6gkjjscy68dv39una68nl3347z0rxhrhqyax27g45yrvjwlgclzmpja = "signam1qqjyg76gts4qtlf4jgam44859zfadc3fuz3h9errxlv5gv2nkqwtyzsxqwjk3x5qt5xtdl2nug3hu7kyxtu2sha02gdpaalk9w4s4lsgm6ehyk"
